# Generated by Django 3.2.9 on 2021-12-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], max_length=20)),
                ('additional_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
