# Generated by Django 3.2.9 on 2021-12-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
